spring:
  application:
    name: eureka-client
  # consul
#  cloud:
#    consul:
#      host: localhost
#      port: 8500

server:
  port: 2002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/