spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xer97/config-repo-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

server:
  port: 1201
